export enum Permisos{
  LAYOUT = "LAYOUT",
  PRODUCTOS = "PRODUCTOS",
  PROVEEDORES = "PROVEEDORES",
  SOLICITUDES = "SOLICITUDES",
  COMPRAS = "COMPRAS",
  INVENTARIO = "INVENTARIO",
  SOLICITUDESADQUISICIONES = "SOLICITUDES ADQUISICIONES",
  COMPRASADQUISICIONES = "COMPRAS ADQUISICIONES",
  INVENTARIOSADQUISICIONES = "INVENTARIOS ADQUISICIONES",
  UNIDAD = "UNIDAD",
  MAXMINSTOCK = "MAX Y MINIMOS STOCK",
  MAXMINEXISTENCIA = "MAX Y MINIMOS EXISTENCIA",
}
