export enum Permisos{
  LAYOUT = "LAYOUT",
  PRODUCTOS = "PRODUCTOS",
  PROVEEDORES = "PROVEEDORES",
  SOLICITUDES = "SOLICITUDES",
  COMPRAS = "COMPRAS",
  INVENTARIO = "INVENTARIO",
  SOLICITUDESADQUISICIONES = "SOLICITUDES-ADQUISICIONES",
  COMPRASADQUISICIONES = "COMPRAS-ADQUISICIONES",
  INVENTARIOSADQUISICIONES = "INVENTARIOS-ADQUISICIONES",
  UNIDADES = "UNIDADES",
  MAXMINSTOCK = "MAXMINSTOCK",
  MAXMINEXISTENCIA = "MAXMINEXISTENCIA",
}
